create table if not exists public.medicamentos (
  id bigint generated by default as identity primary key,
  nombre text not null,
  tipo text not null check (tipo in ('medicamento', 'vacuna')),
  presentacion text not null default '',
  concentracion text not null default '',
  cantidad integer not null default 1 check (cantidad >= 0),
  unidad text not null default 'frascos',
  fecha_caducidad date not null,
  fecha_ingreso date not null default current_date,
  observaciones text not null default '',
  imagen_url text not null default '',
  requiere_receta boolean not null default false,
  es_controlado boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.actividades (
  id bigint generated by default as identity primary key,
  tipo text not null check (tipo in ('entrada', 'salida', 'ajuste', 'caducidad', 'baja')),
  medicamento_id bigint references public.medicamentos(id) on delete set null,
  medicamento text not null default '',
  lote text not null default '',
  cantidad integer,
  descripcion text not null,
  fecha timestamptz not null default now(),
  usuario text not null default 'Sistema',
  created_at timestamptz not null default now()
);

create table if not exists public.usuarios (
  id bigint generated by default as identity primary key,
  nombre text not null,
  email text not null unique,
  password text not null,
  rol text not null default 'visualizador' check (rol in ('admin', 'veterinario', 'tecnico', 'visualizador')),
  activo boolean not null default true,
  ultimo_acceso timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Usuarios iniciales: cambia estas contraseñas antes de publicar.
-- admin@ganadero.com / admin123
-- vet@ganadero.com / vet123
-- tecnico@ganadero.com / tecnico123
insert into public.usuarios (nombre, email, password, rol) values
  ('Administrador', 'admin@ganadero.com', '$2y$12$dod/U.5UtkZod6N32RpnT.c7ZjYueOCAyrlJLIhmVMC2kPZbicUv.', 'admin'),
  ('Dr. Veterinario', 'vet@ganadero.com', '$2y$12$tQxK.KgwH2quCzAybrRfruCXGr9i6CD.qZLOtoPcPR/6J//3TZeE6', 'veterinario'),
  ('Técnico Ganadero', 'tecnico@ganadero.com', '$2y$12$fCNHmXqnaFMAH7ir9JlSTuLsr4vrfvXmFzNgTJCJuWQ6PEpaMOgJi', 'tecnico')
on conflict (email) do nothing;

create index if not exists medicamentos_caducidad_idx on public.medicamentos(fecha_caducidad);
create index if not exists actividades_fecha_idx on public.actividades(fecha desc);

alter table public.medicamentos enable row level security;
alter table public.actividades enable row level security;
alter table public.usuarios enable row level security;

create or replace function public.operar_inventario(
  p_medicamento_id bigint,
  p_tipo text,
  p_cantidad integer,
  p_usuario text
) returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  producto medicamentos%rowtype;
  actividad actividades%rowtype;
  cantidad_resultante integer;
begin
  if p_tipo not in ('baja', 'salida', 'ajuste') then
    raise exception 'Operación inválida';
  end if;

  select * into producto from medicamentos where id = p_medicamento_id for update;
  if not found then
    raise exception 'Producto no encontrado';
  end if;

  if p_tipo = 'salida' then
    if p_cantidad is null or p_cantidad < 1 then raise exception 'La cantidad de salida debe ser mayor que cero'; end if;
    if p_cantidad > producto.cantidad then raise exception 'La cantidad de salida supera el stock disponible'; end if;
    cantidad_resultante := producto.cantidad - p_cantidad;
  elsif p_tipo = 'ajuste' then
    if p_cantidad is null or p_cantidad < 0 then raise exception 'La cantidad ajustada no puede ser negativa'; end if;
    cantidad_resultante := p_cantidad;
  else
    if producto.cantidad < 1 then raise exception 'El producto no tiene stock disponible'; end if;
    cantidad_resultante := 0;
  end if;

  update medicamentos set cantidad = cantidad_resultante, updated_at = now()
  where id = producto.id returning * into producto;

  insert into actividades (tipo, medicamento_id, medicamento, cantidad, descripcion, fecha, usuario)
  values (
    p_tipo, producto.id, producto.nombre,
    case when p_tipo = 'baja' then 0 else p_cantidad end,
    case p_tipo when 'salida' then 'Salida de inventario: ' when 'ajuste' then 'Ajuste de inventario: ' else 'Baja de inventario: ' end || producto.nombre,
    now(), p_usuario
  ) returning * into actividad;

  return jsonb_build_object('medicamento', to_jsonb(producto), 'actividad', to_jsonb(actividad));
end;
$$;

revoke all on function public.operar_inventario(bigint, text, integer, text) from public;
grant execute on function public.operar_inventario(bigint, text, integer, text) to service_role;
